on:
  push:
    branches:
      - master

name: Build and Release Apps
jobs:
  build:
    name: Build Apps
    runs-on: ubuntu-latest
    steps:
      - name: Export Release Timestamp
        run: echo "::set-env name=APP_VERSION::release_$(date +'%Y-%m-%d_%H-%m-%S')"
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: "8.x"
      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.8.1' 
      - name: Install pub Dependencies
        run: flutter pub get
      - name: Build Android App
        run: flutter build apk
      - name: Release Apps
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.APP_VERSION }}
          name: ${{ env.APP_VERSION }}
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "build/app/outputs/apk/release/*.apk"
